FROM node:20-alpine

WORKDIR /app

COPY ./ui/package.json ./ui/package-lock.json ./
RUN npm install

COPY ./ui .

ARG NEXT_PUBLIC_API_BASE_URL

RUN NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL npm run build

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]